ZEQP.Print/Models/ErrorViewModel.cs
using System;

namespace ZEQP.Print.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ZEQP.Print/Controllers/FieldController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ZEQP.Print.Controllers
{
    public class FieldController : Controller
    {
        public IActionResult Index(int id)
        {
            ViewBag.TemplateId = id;
            return View();
        }
    }
}

ZEQP.Print/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ZEQP.Print.Entities;
using ZEQP.Print.Models;

namespace ZEQP.Print.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public PrintContext DbContext { get; set; }
        public HomeController(ILogger<HomeController> logger, PrintContext dbContext)
        {
            _logger = logger;
            this.DbContext = dbContext;
        }

        public IActionResult Index()
        {
            var list = this.DbContext.Templates.ToList();
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ZEQP.Print/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ZEQP.Print.Controllers
{
    public class TaskController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ZEQP.Print/Controllers/TemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ZEQP.Print.Controllers
{
    public class TemplateController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Modify(int id)
        {
            ViewBag.Id = id;
            return View();
        }
    }
}

ZEQP.Print/Views/Field/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutContent.cshtml";
}
<div id="mainApp">
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Profile</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Contact</a>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">Home</div>
    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">Profile</div>
    <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">Contact</div>
</div>
</div>
@section Scripts{
    <script>
        var mainApp = new Vue({
            el:"#mainApp",
            data:{
                Config:{TemplateId:"@ViewBag.TemplateId", CurTable:"Main"},
                TableNames:["Main"],
                ListData:[]
            },
            filters:{},
            mounted: function () {
                this.getFields();qxsdwfssgsgggs        
            },
            methods:{
                getFields(){
                    axios.get("/api/TemplateField/GetFields/" + this.Config.TemplateId)
                        .then(function (response) {
                            this.ListData = response.data;
                        }.bind(this))
                        .catch(function (error) {
                            console.log(error);
                        });
                }
            }
        });
    </script>
}

ZEQP.Print/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ZEQP.Print/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 中南智能文档打印系统</title>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/layer/skin/layer.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">文档打印</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Task</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Template" asp-action="Index">Template</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - 中南智能文档打印系统 - 工业软件中心
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/vue/vue.js"></script>
    <script src="~/lib/moment/moment.js"></script>
    <script src="~/lib/axios/axios.js"></script>
    <script src="~/lib/layer/layer.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ZEQP.Print/Views/Shared/_LayoutContent.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 中南智能文档打印系统</title>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/layer/skin/layer.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid">
        @RenderBody()
    </div>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/vue/vue.js"></script>
    <script src="~/lib/moment/moment.js"></script>
    <script src="~/lib/axios/axios.js"></script>
    <script src="~/lib/layer/layer.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ZEQP.Print/Views/Task/Index.cshtml
@{
    ViewData["Title"] = "打印任务";
}

<h1>Index</h1>

ZEQP.Print/Views/Template/Index.cshtml
@{
    ViewData["Title"] = "文档模板";
}
<div class="card" id="mainApp">
    <h5 class="card-header">文档模板</h5>
    <div class="card-body" v-bind:style="{height:tableHeight+'px'}">
        <div class="card">
            <div class="card-body">
                <form class="form-inline">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">名称/编码:</span>
                        </div>
                        <input type="text" class="form-control" placeholder="模板名称/编码" v-model="PageQuery.Match">
                    </div>
                    <div class="input-group ml-2">
                        <div class="input-group-prepend">
                            <span class="input-group-text">状态:</span>
                        </div>
                        <select class="form-control" v-model="PageQuery.Query.Status">
                            <option value="">所有</option>
                            <option value="Enable">启用</option>
                            <option value="Disable">禁用</option>
                        </select>
                    </div>
                    <button type="button" class="btn btn-primary ml-2" v-on:click="getListData">查询</button>
                    <button type="button" class="btn btn-success ml-2" v-on:click="showModify(0)">新增</button>
                </form>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <td>名称</td>
                    <td>编码</td>
                    <td>版本</td>
                    <td>保存文件?</td>
                    <td>打印次数</td>
                    <td>状态</td>
                    <td>创建时间</td>
                    <td>修改时间</td>
                    <td>操作</td>
                </tr>
            </thead>
            <tbody>
                <tr v-for="item in ListData" v-bind:key="item.Id">
                    <td>{{item.Name}}</td>
                    <td>{{item.Code}}</td>
                    <td>{{item.Verstion}}</td>
                    <td>{{item.SaveToFile}}</td>
                    <td>{{item.PrintCount}}</td>
                    <td>{{item.Status}}</td>
                    <td>{{item.CreateTime | datetime}}</td>
                    <td>{{item.ModifyTime | datetime}}</td>
                    <td>
                        <a href="javascript:;" v-on:click="showModify(item.Id)">修改</a>
                        <a href="javascript:;" v-on:click="showField(item.Id)">字段</a>
                        <a :href="item.Path" target="_blank" class="ml-1">下载</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="card-footer text-muted" style="padding: 0 1.25rem;">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li class="page-item"><a class="page-link" href="javascript:;" v-on:click="getPage(1)">首页</a></li>
                <li class="page-item"><a class="page-link" href="javascript:;" v-on:click="getPage(PageQuery.Page-1)">上一页</a></li>
                <li class="page-item disabled"><a class="page-link" href="javascript:;">{{PageQuery.Page}}/{{totalPages}}({{Config.TotalRows}})</a></li>
                <li class="page-item"><a class="page-link" href="javascript:;" v-on:click="getPage(PageQuery.Page+1)">下一页</a></li>
                <li class="page-item"><a class="page-link" href="javascript:;" v-on:click="getPage(totalPages)">尾页</a></li>
            </ul>
        </nav>
    </div>
</div>
@section Scripts{
    <script>
        var mainApp = new Vue({
            el: "#mainApp",
            data: {
                Config: { WindowHeight: window.innerHeight, TotalRows: 0 },
                PageQuery: {
                    Size: 10, Page: 1, Order: "ModifyTime", Sort: "DESC", Match: "", Query: { Status: null }
                },
                ListData: []
            },
            mounted: function () {
                this.$nextTick(() => {
                    window.addEventListener('resize', () => {
                        this.Config.WindowHeight = window.innerHeight;
                    });
                });
                this.getListData();
            },
            computed: {
                totalPages: function () {
                    return this.Config.TotalRows % this.PageQuery.Size
                        ? parseInt(this.Config.TotalRows / this.PageQuery.Size) + 1
                        : this.Config.TotalRows / this.PageQuery.Size;
                },
                tableHeight: function () {
                    return this.Config.WindowHeight - 260;
                }
            },
            filters: {
                date: function (value) {
                    return moment(value).format("YYYY-MM-DD");
                },
                datetime: function (value) {
                    return moment(value).format("YYYY-MM-DD HH:mm:ss");
                }
            },
            methods: {
                getListData: function () {
                    axios.post("/api/Template/GetPage", this.PageQuery)
                        .then(function (response) {
                            var result = response.data;
                            this.ListData = result.Data;
                            this.Config.TotalRows = result.Count;
                            this.PageQuery.Page = result.Page;
                        }.bind(this))
                        .catch(function (error) {
                            console.log(error);
                        });
                },
                getTotalPages() {
                    return this.Config.TotalRows % this.PageQuery.Size
                        ? parseInt(this.Config.TotalRows / this.PageQuery.Size) + 1
                        : this.Config.TotalRows / this.PageQuery.Size;
                },
                getPage(index) {
                    var totalPages = this.getTotalPages();
                    this.PageQuery.Page = index;
                    if (index <= 0) this.PageQuery.Page = 1;
                    if (index > totalPages) this.PageQuery.Page = totalPages;
                    this.getListData();
                },
                showModify(id) {
                    layer.open({
                        type: 2,
                        title: '编辑',
                        shadeClose: true,
                        area: ['600px', '450px'],
                        content: '/Template/Modify/' + id
                    });
                },
                showField(id){
                    layer.open({
                        type: 2,
                        title: '字段管理',
                        shadeClose: true,
                        area: ['800px', '600px'],
                        content: '/Field/Index/' + id
                    });
                }
            }
        });
    </script>
}

ZEQP.Print/Views/Template/Modify.cshtml
@{
    ViewData["Title"] = "Modify";
    Layout = "~/Views/Shared/_LayoutContent.cshtml";
}

<form id="mainApp">
    <input type="hidden" v-model="Model.Id" />
    <div class="form-group row">
        <label for="txtName" class="col-sm-2 col-md-2 col-form-label">模板名称</label>
        <div class="col-sm-10 col-md-10">
            <input type="text" class="form-control" id="txtName" v-model="Model.Name">
        </div>
    </div>
    <div class="form-group row">
        <label for="txtCode" class="col-sm-2 col-md-2 col-form-label">模板编码</label>
        <div class="col-sm-10 col-md-10">
            <input type="text" class="form-control" id="txtCode" v-model="Model.Code">
        </div>
    </div>
    <div class="form-group row">
        <label for="txtVerstion" class="col-sm-2 col-md-2 col-form-label">模板版本</label>
        <div class="col-sm-10 col-md-10">
            <input type="text" class="form-control" id="txtVerstion" v-model="Model.Verstion">
        </div>
    </div>
    <div class="form-group row">
        <label for="txtPath" class="col-sm-2 col-md-2 col-form-label">上传模板</label>
        <div class="col-sm-10 col-md-10">
            <input type="file" class="form-control-file" id="txtPath" ref="file" v-on:change="fileUpload()">
        </div>
    </div>
    <div class="form-group">
        <div class="form-check col-sm-10 col-md-10 offset-2">
            <input class="form-check-input" type="checkbox" id="ckbSaveToFile" v-model="Model.SaveToFile">
            <label class="form-check-label" for="ckbSaveToFile">保存打印历史</label>
        </div>
    </div>
    <div class="form-group row">
        <label for="txtVerstion" class="col-sm-2 col-md-2 col-form-label">状态</label>
        <div class="col-sm-10 col-md-10">
            <select class="form-control" v-model="Model.Status">
                <option value="1">启用</option>
                <option value="2">禁用</option>
            </select>
        </div>
    </div>
    <button type="button" class="btn btn-primary" v-on:click="submit()">保存</button>
</form>
@section Scripts{
    <script>
        var mainApp = new Vue({
            el: "#mainApp",
            data: {
                Model: { "Id": 0, "Name": "", "Code": "", "Verstion": "", "Path": null, "SaveToFile": false, "PrintCount": 0, "Status": 1, "CreateTime": moment(), "ModifyTime": moment() },
                Config: { WindowHeight: window.innerHeight, TotalRows: 0, file: null }
            },
            mounted: function () {
                var id = parseInt("@ViewBag.Id");
                if (id > 0) {
                    axios.get("/api/Template/Get/" + id)
                        .then(function (response) {
                            var result = response.data;
                            this.Model = result;
                        }.bind(this))
                        .catch(function (error) {
                            console.log(error);
                        });
                }
            },
            computed: { },
            filters: {
                date: function (value) {
                    return moment(value).format("YYYY-MM-DD");
                },
                datetime: function (value) {
                    return moment(value).format("YYYY-MM-DD HH:mm:ss");
                }
            },
            methods: {
                submit: function () {
                    axios.post("/api/Template/Modify", this.Model)
                        .then(function (response) {
                            var result = response.data;
                            this.Model = result.Data;
                            layer.alert(result.Msg);
                        }.bind(this))
                        .catch(function (error) {
                            console.log(error);
                        });
                },
                fileUpload: function () {
                    debugger;
                    this.file = this.$refs.file.files[0];
                    let formData = new FormData();
                    formData.append('tempFile', this.file);
                    axios.post('/api/Template/Upload',
                        formData,
                        {
                            headers: {
                                'Content-Type': 'multipart/form-data'
                            }
                        }
                    ).then(function (response) {
                        var result = response.data;
                        console.log(result);
                        if (result.Success)
                            this.Model.Path = result.Data;
                        layer.alert(result.Msg);
                    }.bind(this))
                        .catch(function () {
                            console.log('FAILURE!!');
                        });
                }
            }
        });
    </script>
}